### ISSUE TITLE
Installation/use documentation?

### ISSUE THREAD

**Issue by rnjudge** [bom-squad/protobom#101]
The repo is missing directions for how to install and utilize the protobom tool/library.

**Comment by jspeed-meyers** [comment]
Thanks, @rnjudge! This would indeed be helpful.

To anyone reading this: PR welcome!

**Comment by veramine** [comment]
I took a crack at this.  https://github.com/bom-squad/protobom/pull/107

**Comment by jspeed-meyers** [comment]
@rnjudge, if you have a moment to spare, I'd be curious if this is helpful to you?

**Comment by veramine** [comment]
A little birdie told me Rose maaaaay be at the same conference @puerco is attending this week.  ;)

**Comment by jspeed-meyers** [comment]
@rnjudge is usually five SBOM steps ahead of me. As is @puerco :)

**Comment by rnjudge** [comment]
@veramine First of all, thank you so much for your PR. Second of all, your birdie has good intel. I saw @puerco today and will review this ASAP but just from a glance, it looks incredibly helpful!

**Comment by jspeed-meyers** [comment]
I'm going to close this given the PR mentioned above merged. But if there are ways to improve the installation and usage documentation, please feel free to create a new issue, @rnjudge!
