### ISSUE TITLE
Unserialize SPDX v2.2 to Protobom

### ISSUE THREAD

**Issue by veramine** [bom-squad/protobom#105]
I'm trying to use the library to compare vendor-published SBOMs vs SBOMs generated by the Veramine tool.  There aren't many for Windows software.  And unfortunately Microsoft's tool (https://github.com/microsoft/sbom-tool) creates SPDX v2.2 SBOMs.

How difficult would it to be to add support for SPDX v2.2 JSON format SBOM's?  Even if there was only support for unserializing, not serializing, that would be enough for my particular use case.  I see https://github.com/spdx/tools-golang/tree/main/spdx/v2/v2_2 exists...

**Comment by puerco** [comment]
I'll add this one as soon as we're done with the refactoring going on in #104

**Comment by veramine** [comment]
Thank you!
