### ISSUE TITLE
Component type / Primary purpose enummeration

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#124]
:warning: **Possible breaking change** ⚠️ 

We have been capturing all enumerated values into Enums in the protobuf model. One that is missing is the `primary_purpose` field that gets rendered as the [component type](https://cyclonedx.org/docs/1.4/json/#components_items_type) in CycloneDX and as the [Primary Purpose field](https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field) in SPDX packages. It is currently a sring:

https://github.com/bom-squad/protobom/blob/aa6ebbd17bb8ff086558ac6098f9a7dc66f76f2f/api/sbom.proto#L33

We could shrink the protobuf message size more if we enumerate the values in this field just as we did with hash algorithms, lifecycles, etc.

Since we're freezing the API on v0.2.0 this could be a good time to introduce this change as it would break the model again. Thoughts?

**Comment by veramine** [comment]
Yes... I'm in favor.   It's the last place we are doing something like this..

```
switch strings.ToLower(something)
case "foo"
...
```

We can get this done today if you want.
