### ISSUE TITLE
spdx-Cyclonedx root missing

### ISSUE THREAD

**Issue by houdini91** [bom-squad/protobom#13]
Seem the metadata.component root of the cyclonedx writer is missing, 
Seems like it not found in the nodes list using the ID of the RootElements.

**Comment by houdini91** [comment]
go run cmd/demo-ingest/main.go examples/vt.spdx.json 

```
  "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "SPDXRef-DOCUMENT",
  "version": 0,
  "metadata": {
    "component": { <--- Empty
      "type": "application",
      "name": ""
    }
  },
...
```

**Comment by jspeed-meyers** [comment]
cc @puerco

**Comment by houdini91** [comment]
It seems like this is not a bug but rather a possible options.
if i understand correctly @puerco Correct me if i am wrong.
Spdx can have ether 0,1 or many root components,
Further more i was assuming a root component is required in CDX but it turns out it is not.
I think we can close this bug
