### ISSUE TITLE
External reference type should be enumerated

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#148]
In our current model, the external reference type is a string:

https://github.com/bom-squad/protobom/blob/3dff6b2828bc60a260f8f8ddfdb7389b66844d1b/api/sbom.proto#L130-L139

Given that both formats enumerate the valid values we should also have an enumerated field.

**Comment by veramine** [comment]
I asked chatgpt for list of valid values and got these:

SPDX:

* cpe22Type: This reference type is used for specifying a CPE (Common Platform Enumeration) version 2.2 identifier.
* cpe23Type: Similar to cpe22Type, but for CPE version 2.3 identifiers.
* maven-central: This reference is used for artifacts that are stored in Maven Central, typically for Java libraries.
* npm: This reference type is for packages that are available in the npm (Node Package Manager) registry.
* nuget: Refers to packages available in the NuGet gallery, commonly used for .NET packages.
* bower: For components that are available in the Bower registry, a package manager for front-end web development.
* purl: Package URLs (purl) provide a standard way to identify and locate software packages across different package managers and registries.
* swidTagID: Refers to the SWID (Software Identification) Tag ID as per ISO/IEC 19770-2:2015 standards.
* git: This reference is for Git repositories, specifying a particular commit, branch, or tag.
* other: A catch-all category for references that don't fit into the other types, allowing for flexibility and future expansion.

CycloneDX:

* vcs: Version Control System reference. It's used to point to the source code repository of the component.
* issue-tracker: Reference to the issue tracker associated with the component (e.g., JIRA, GitHub issues).
* website: A reference to the official website or webpage for the component.
* advisories: Used to link to published advisories related to the component.
* bom: This type of reference points to another SBOM that is related to the component.
* mailing-list: Reference to a mailing list that is relevant to the component.
* social: Refers to social media or other online platforms where discussions or information about the component can be found.
* chat: Reference to a chat platform or channel related to the component (e.g., Slack channels, IRC).
* documentation: Links to the official documentation of the component.
* support: Reference to support resources for the component, such as help desks or support forums.
* distribution: Used to reference a distribution point for the component, like a package registry or download page.
* license: A reference to the license details of the component.
* build-meta: Reference to build metadata.
* build-system: Points to the system or tool used for building the component.
* other: A catch-all category for references that don't fit into the other types, similar to SPDX.

Do these seem right?  If so, I can handle this issue.

**Comment by puerco** [comment]
Thanks @veramine ! I am working on it just now. Oh and the bot got the values wrong. I'm finishing the mapping here:
https://docs.google.com/spreadsheets/d/1UFz8V-HrUMN0VnTNsXhrmPLDx6eYECBnGgunZ65nDtE/edit?usp=sharing

**Comment by veramine** [comment]
cool man, thanks!  carry on ;)
