### ISSUE TITLE
Add Basic Instructions for Usage (and perhaps dev and testing)

### ISSUE THREAD

**Issue by jspeed-meyers** [bom-squad/protobom#17]
How should a developer intending to try this code out, or do development and testing, proceed?

For instance, when I run:

`$ go run cmd/demo-ingest/main.go`

I get:

```
FATA[0000] usage: /var/folders/km/_02qm7_51n17hg3v6byj1wrm0000gn/T/go-build1444193302/b001/exe/main sbom.json 
exit status 1
```

Am I holding it wrong? Without further instructions, I'm just guessing.

**Comment by jspeed-meyers** [comment]
I was holding it wrong! :)

After poking around the code, I discovered that this command requires a path to an SBOM:

`go run cmd/demo-ingest/main.go examples/curl.spdx.json`

A little documentation would prevent each of us from going through these same steps

**Comment by houdini91** [comment]
Related PR https://github.com/bom-squad/protobom/pull/19

**Comment by jspeed-meyers** [comment]
Since the CLI has been moved out of `protobom`, I'll close this for now. There should probably be better documentation for developers that want to use `protobom` as a library though, I think. My 2 cents.
