### ISSUE TITLE
Conversion Issue: CycloneDX components without bomRef

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#23]
## Problem:

protobom relies on the iDs in Nodes to structure its document representation. However, [CycloneDX allows elements to exist without `bomRef`](https://cyclonedx.org/docs/1.4/json/#components_items_bom-ref). This poses a fidelity problem. 

## Proposal

Since Node IDs are required in protobom and also mandatory in SPDX, this proposal suggest handling bomref-less data to/from CDX documents in the following way:

### Ingestion: 

When ingesting components without a ref in CycloneDX, protobom will generate the missing ID (bomRef) for the component with a string with a prefix that lets the tooling know that the id is a) generated by protobom and b) belongs to a component without a bomRef.

An example of such an ID could be:

`__protobom_auto_noref-b51261db1ecadecf85274e811e537c5811a0ad1ab2a0121aeac4e3d031e1bf83`

An example of a Node with that id would be:

```go
node := &Node {
   Id: "__protobom-auto-noref--b51261db1ecadecf85274e811e537c5811a0ad1ab2a0121aeac4e3d031e1bf83-1",
  Name: "My bomRefLess component",
  Version: "v1.0.0",
}
```

The autogenerated id has the following parts:

- `__protobom`: Lets protobom know that the ID was added by protobom
- `-auto`: Denotes the ID was autogenerated at ingestion
- `-noref`: Denotes that the node originally had no bomRef.
- Two dashes followed by a SHA256 hash
- `-1` A serial number

The hash appended at the end is generated from the `document.Id`. It is appended by a `_1` which is a serial number incremented each time an Id is generated. This mechanism makes the IDs reproducible when re-ingesting the same SBOM.

### Serialization

When serializing a protobom with autogenerated IDs, the tooling can use the hints in the ID to decide how to process those IDs. The first step is stripping the dual underscores. The, depending on the format:

In the specific case of CDX nodes that originally had no bomRef, the protobom tooling can detect the `_noref` bit in the ID and simply avoid assigning it to the serialized document.

When serializing to other formats the autogenerated id can go in verbatim after removing the initial underscores. For example in SPDX:

```json
  "packages": [
    {
      "SPDXID": "SPDXRef-protobom-auto-noref--b51261db1ecadecf85274e811e537c5811a0ad1ab2a0121aeac4e3d031e1bf83-1",
      "name": "logsave",
      "versionInfo": "1.46.2-2",
      "filesAnalyzed": false,
      "downloadLocation": "NONE",
    }
]
```

**Comment by veramine** [comment]
I love the idea of protobom providing reasonable default values for our required fields, and those default values being specific to the document at ingestion.  Anything we can do to accept more and crappier sbom's for ingestion for our required fields is work worth doing, in my opinion.  Would it be worth it to note somewhere in our protobuf and the resulting converted document the list of fields that we automatically generated?

**Comment by puerco** [comment]
I think so, I've been noodling on ways to somehow craft a report of any serialization problems after writing, but something that is actually useful and actionable (meaning not just a .txt or messages on stderr). I think we need to start using the libraries in a simple converter (such as Mikey's cli in https://github.com/bom-squad/protobom/pull/19)  to imagine how that would work.

**Comment by houdini91** [comment]
I agree we sould generate the missing refs it's mostly used internally to the sbom so It probably won't harm anybody.

I find using a uri with some random param instead of a hardcoded string is clearer.

Github.com/protobom?uuid=random&serial=...

**Comment by dn-scribe** [comment]
@puerco I like the reproducibility feature/req, it enables file-compare and so,  though a serial number may not be a good solution; JSON does not require keeping order of sub-objects, and there could be a case in which two runs of some external tool will produce different-ordered lists.

In addition, I'd rather use the bom-ref for something that encodes more info.
I suggest dropping the doc-id-hash, and taking in the component type-group-name-version. I know this suggestion does not yet provide a uniqe identifier, so I suggest adding the component-data, and if the hash is not uniqe, simply drop that component (it is identical to another, and has no bomRef so no dependency will ref it - It is redundant).

**Comment by dn-scribe** [comment]
@puerco please update the spec doc according to this issue. It will be availabe quite soon.
