### ISSUE TITLE
Serializer Conformance Testing

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#24]
## Problem:

We need to ensure the serializers create SBOMs consistently, with the expected degradation and structure.

## Proposal

We should create a collection of golden documents, each with different characteristics and challenges for the serializer. Some examples include: documents missing IDs, documents missing root nodes, documents with broken edges, etc.

Conformance tests would load the raw proto, feed the document into the serializer to generate a document in each format. If we have options for the serializers we should test all scenarios.

Paired with native tools to extract data from the documents (both SBOM tools and more lower level utilities like `jq` we then extract data from the documents:

![image](https://github.com/bom-squad/protobom/assets/3935899/3f606544-b3a4-4a90-b023-27b862a9b8e2)

Using this corpus of data, the generated documents and the tools we need, we create three kinds of tests:

1. **Reference Tests**<br>
These tests take the generated document and compare the data against the known features of the golden documents. This includes checking the number of packages, structure of the SBOM, edges, top level nodes, 

2. **Format Data Tests**<br>
These tests have to do with data specific to each format: Are the SPDX relationships sound? Is the CycloneDX dependency tree complete? Is the supplier data in the documents correct? Is the SPDX package verification code correct? etc.

3. **Format Conformance Tests**<br>
These tests mean running the "official" format validators against t the generated documents to ensure the serializer/writer pair is generating valid syntax.

## Open Questions

- Should we scaffold the tests early or wait until the serializers are more or less "complete"?

**Comment by jspeed-meyers** [comment]
cc @houdini91 -- I'd be curious for your take here.
