### ISSUE TITLE
Command-Line Interface discussion 

### ISSUE THREAD

**Issue by houdini91** [bom-squad/protobom#25]
IMHO it would be beneficial to discuss the user interface as soon as possible. By doing this early on, we can establish a skeleton application and moving parts protobom will need.

Below are some points and suggestions for designing a basic CLI (Command-Line Interface) tool, assuming we decide to implement one. Please take these suggestions with caution, as they are influenced by my personal styles.

**Target:**
Our goal is to provide users with an accessible entry point to all the translation flows that Protobom offers.

**CLI Repository:**
We need to determine the repository where we can host the source code for the CLI. Additionally, we can address how it will access the Protobom-generated library.

**Implementation:**
We can build the CLI using Golang.

**User Interface:**
- Command-Line Flags: The main interface to the CLI can be command-line flags.
- Configuration: We can consider whether configuration as code and reusable setting are necessary for our CLI. While implementing this feature may not require significant effort, we should discuss its importance.
- Output: CLI output is a SBOM with the resulted translated SBOM on-disk or in stdout.
- Logging: CLI can include logs on what happened or what when horribly wrong (i suggest we define a interface rather than using a specific library so we can switch out the loggers).

**Build:**
We can build the CLI as both a binary and an image. This approach offers extensive support for platform integration and user convenience. Furthermore, it serves as the foundation for any other packaged applications we may choose to develop.

- Binary Output:
  - Architectures: amd64, arm64
  - Operating Systems: Linux, Windows, Mac

- Image Output:
  - Architectures: amd64, arm64

We can use **Goreleaser** (free version, no need for the pro version) as a framework to build our CLI. It has been very efficient to me in bootstrapping Golang-based applications.

**Testing:**
- Unit Tests: We can strive to have basic unit tests for the libraries we host. I recommend using the Go testing framework for this purpose.

- CLI Integration Tests: We can simulate user CLI test cases and use test data to verify full flows. Using the Go testing framework for integration tests would be more convenient than using two separate frameworks.

- Liting golangci-lint https://github.com/bom-squad/protobom/issues/16

**Versions:**
We can synchronize CLI versions with Git tags on the main branch.
Suggestion version format `vX.Y.Z` or `vX.Y.Z-T`, For Example: `v0.2.0` < `v0.2.0-1`.

Should we use semantic versioning rules, what are the guidelines for backward compatibility, changelog ?

**Releases:**
- Release Binaries: We can publish release binaries to GitHub releases.
- Release Image: We can make the release image available on Dockerhub. Please note that this requires a Bom-Squad account.
- Bonus: sign our releases artifacts, we can use Cosign using our github workflow identity.

**Install:**
- Download from gihthub Releases
- Install from source (go install github.com/bom-squad ..)
- Pull image from registry (docker pull ...)

**Continuous Integration:**
We can leverage GitHub-based CI for our project, with the following workflows:
- Integration: Triggered upon pull requests to the main branch.
- Unit Tests: Triggered when a pull request is opened.
- Release: Triggered when a tag is created on the main branch.

Notifications: We should set up a Slack channel for receiving CI notifications.

**Comment by jspeed-meyers** [comment]
@bardenstein -- I thought this issue might particularly be of interest to you!

**Comment by bardenstein** [comment]
@jspeed-meyers indeed! 

@houdini91 I'm finally touching up the user specs for the project, and specifically the cli, let's collaborate so we're all on the same page. I've taken first steps more focusing on the interface, the process (testing, install, etc.) happy to defer to you and others.

**Comment by jspeed-meyers** [comment]
> Unit Tests: We can strive to have basic unit tests for the libraries we host. I recommend using the Go testing framework for this purpose.

Sounds good to me!

**Comment by jspeed-meyers** [comment]
> We can build the CLI using Golang.

Also sounds good to me!

**Comment by jspeed-meyers** [comment]
> Should we use semantic versioning rules

And I personally like semantic versioning and so support that!

**Comment by bardenstein** [comment]
@houdini91 specs for this feature are being tracked here -they're still in progress for the library, but have more info re the cli. 

Feel free to comment or add!

https://www.notion.so/manifestcyber/Project-Spec-SBOM-Translator-d2011cacbb94467997b8b971e6972e49?pvs=4
