### ISSUE TITLE
Confirm: should (library || cli) support multiple input SBOMs?

### ISSUE THREAD

**Issue by bardenstein** [bom-squad/protobom#29]
Just to confirm: 
do we want the desired behavior to be that, as a user, I can submit multiple SBOMs (of different formats/versions) at the same time? 

Seems like a win for the user, but just adds a little more work to the effort.

**Comment by jspeed-meyers** [comment]
Why not just call the library or CLI command multiple times? For me, this seems potentially unnecessary. But I'm not hard over on it.

**Comment by dn-scribe** [comment]
I agree with @jspeed-meyers , 
supporting multiple requires more complicated testing and a much more complicated configuration (need to support multiple configs). 
Lets leave it simple.

**Comment by veramine** [comment]
I don't think this is worth spending time on at the moment.  Closing for now.  Please re-open if a compelling use case calls for it.  Thanks!
