### ISSUE TITLE
spdx-CycloneDX conversion issue: document-creation-data: external references 

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#35]
[External document references](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#66-external-document-references-field)

Issue:
 - This spdx field is intended for a list of external SPDX docs, referenced within the doc. CycloneDX has a externalReferences object for components, but the relevant type is "bom" which does not indicate if it is an SPDX doc.

Suggestions
 - Default: This field will not be populated. It is intended for other spdx documents, and these are not expected in a cycloneDX document.
 - use config.spdx.externalReferences

Notes:

In the future this filed can be populated from cycloneDX.components[]externalReferences if the externalReference type is bom and it is an SPDX document. This requires access to the SPDX document, that I don't think we will have.

the cyclondDX.externalReferences field has a different meaning (it is a list of external relevan docs, and not a list of references used inside the SBOM)

**Comment by stevespringett** [comment]
> the cyclondDX.externalReferences field has a different meaning (it is a list of external relevan docs, and not a list of references used inside the SBOM)

That is not accurate. “External” simply means from the object itself. External references can be URLs or URNs. BOM-Link establishes relationships between objects in the same BOM or external BOMs. External References in CDX are dual purpose and essentially perform the same task as relationships in SPDX.

Consult the relationship chapter for more information and examples. https://cyclonedx.org/guides/sbom/OWASP_CycloneDX-SBOM-Guide-en.pdf

**Comment by dn-scribe** [comment]
Following @stevespringett comment - it is a great explanation but does not solve the spec decision required; the SPDX spec requires specifying links to other relevant SPDX Docs, and it is not simple to understand from the CDX which are they.

The suggested design decision:
1. Default: This field will not be populated. It is intended for other spdx documents, and these are not expected in a cycloneDX document.
2. use config.spdx.externalReferences


Lets discuss this on one of the upcoming meetings.
