### ISSUE TITLE
Normalize license when importing to protobuf

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#38]
The Issue:
CycloneDX has two options to supply license info - either id (spdx-list as source-of-truth for ids) or name that does not have constraints. see [here](https://cyclonedx.org/docs/1.4/json/#tab-pane_metadata_component_licenses_items_license_oneOf_i1)

Since spdx expects using the ids, there is a need to (try to) convert license names to id's.
From my expereinces - there is a good reason to use ids - the names are not normalized - you can find Apache-2.0 (id) or Apache 2 or Apache-2 or Apache 2.0 an so on.

Options: 
 1. have some normalization capability. 
 2. if cdx input had no id - assume it is not spdx licesne (harsh...)

**Comment by jspeed-meyers** [comment]
@dn-scribe, does the current CycloneDX reader in `protobom` losslessly ingest CycloneDX license info? My theoretical understanding is it does. Do I have that right? cc @puerco 

For me, a restatement of your question is the SPDX writer should write out license information from the `protobom` protobuf? Do you like the current implementation?

**Comment by dn-scribe** [comment]
Restating according to @jspeed-meyers comment:

1. Spec level: There is a need to do licneses normalization in the translation process. This is a requirement.
2. Implementation Level: The question is whether this normalization is the role of the writer or the reader? 

I agree that the reader should be "high-fidelity" and modifications should be done when writing; This would enable better testing (do read-write and get the same results), and supporting different use cases (read cdx 1.4 and write 1.5 - no crucial need to normalize license). 

If we have a "design principles" doc - the "high-fidelity-reader-principle" should go there.

**Comment by dn-scribe** [comment]
Regarding implementation, here is a python snippet I wrote once; It generates variations of license names. These are variations I've seen out in the wild. There is room for other variations.
The idea is to generate, in advance, from the spdx-license-list the common variations, and have a lookup table for the use of writers.

```python
def get_canonized_list(license):
    id = license["licenseId"]
    l = []
    # Add identity relation
    l.append([id, id])
    # Add upper case
    l.append([id.upper(), id])
    # Add lower case
    l.append([id.lower(), id])
    # Add spaces instead of dashes
    l.append([id.lower().replace("-", " "), id])
    # Add commas instead of dashes
    l.append([id.lower().replace("-", ", "), id])
    # Add underscores instead of dashes
    l.append([id.lower().replace("-", "_"), id])
    # Add numbers without .0
    l.append([id.lower().replace(".0", ""), id])
    # Add name + 'license'
    l.append([id.lower() + ' license', id])
    # Add full name
    l.append([license["name"], id])
    # Add full name upper case
    l.append([license["name"].upper(), id])
    # Add full name lower case
    l.append([license["name"].lower(), id])
    # Add full name + the word version
    l.append([license["name"].lower().replace("version", "license version"), id])
    # Add full name without .0
    l.append([license["name"].lower().replace(".0", ""), id])
    # Add full name with paranthesis
    l.append(['"' + license["name"].lower() + '"', id])

    return l

```

**Comment by puerco** [comment]
based on our discussion on jul-18 here's the proposed behavior:

CDX has a machine-readable [field for license identifiers that takes the SPDX identifiers](https://cyclonedx.org/docs/1.4/json/#components_items_licenses_items_license_id).  It can also take [license expressions](https://cyclonedx.org/docs/1.4/json/#components_items_licenses_items_expression). 

- License data in CDX identified by an ID will be checked against the latest SPDX license list and used as they are if valid.
- License expressions in CDX will be evaluated. If correct they will be used ingested also as they are.
- Licenses listed by name or with an invalid identifier label will be rendered as as custom licenses when rendering documents.

As the translation layer only needs to relocate data read in other formats, we will not normalizae or transform. Having protobom, it is now trivial to create another utility that can do license normalization if needed. That potential utility could be chained with the translation cli (and others this project could produce) if needed, something like:

```
cat sbom.cdx.json | license-normalize | sbom-translate  > sbom.spdx.json
```
