### ISSUE TITLE
Object Identifiers

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#4]
Hi,
I saw that in the spdx reader identifiers are handled as:
``` 
		Id:                 strings.TrimPrefix(spdxFile.ID, spdx23.IDPrefix),
```

1. I fully agree the original id's information should be preserved.
2. Why trim?

**Comment by puerco** [comment]
I fully agree that we should not modify the data at all.
However, in this case, you need to trim the mandatory `SPDXRef-` prefix from the identifier strings as it is not considered part of the identifier string, see here how the official go libraries do it:

https://github.com/spdx/tools-golang/blob/4b477e88fcb3d02aa302d976bc3768f4e34c5ca3/spdx/v2/v2_3/rdf/reader/utils.go#L118-L140

**Comment by dn-scribe** [comment]
The motivation of leaving in intact is to enable easy verifying and
comparing by running simple "jq | grep ..." like commands, or copy-paste to
a search window.

I would enable two options in config and we can discuss the defalut

בתאריך יום ו׳, 16 ביוני 2023, 0:22, מאת Puerco ***@***.***>:

**Comment by jspeed-meyers** [comment]
@dn-scribe (and others), does such a "config" already exist? If not, feel free to start a PR for such a config. And if it does exist, same but for these proposed options in order to make the proposal code-concrete. Thank you for opening all these issues!

**Comment by dn-scribe** [comment]
@jspeed-meyers 
The config is going to be part of the next discussion and then we will decide how to proceed. My analysis assuemed there will be such a config, but that tranlation should have a default config so a "hands-free" transation can be achieved.

**Comment by dn-scribe** [comment]
An oposite design consideration (oposite to my [comment](https://github.com/bom-squad/protobom/issues/4#issuecomment-1594102182)):

If one would like to support some sort of file-compare, it makes sense to used an in-sbom identifier name scheme (a requirement could be: a file compare to two sboms of the same software artficat should differ only in the fields that have modified: time and date, document id etc. but not in fields that represent components that are the same.).

So there are a few design consideration for our next discussion.

**Comment by dn-scribe** [comment]
I'd like us to discuss the file-comparison "reqruirement" - if and how far would we want to go in order to enable simple file-comparison operations on the generated SBOMS.
