### ISSUE TITLE
cycloneDX-spdx conversion issues: Document Idetifier

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#5]
[SPDXID](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field)
This is supposed to be a unique identifier to the spdx document.
The equivalent it cycloneDX is [serialNumber](https://cyclonedx.org/docs/1.4/json/#serialNumber)

In SPDX it is a required field. In CycloneDX it is not requiered.

Issues:
1. How to fill it.
2. Should it be unique per-conversion

Suggestion:

- spdx.SPDXID = config.spdx.SPDXID, default to:

    - "SPDX"+ date+time + cycloneDX.serialNumber (if exists)
    - date + time in the standard UTC format as described [here](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field)

**Comment by veramine** [comment]
Could we review some sample SBOMs to see how serial number and document identifiers are created.  I've seen some use a hash of the package archive itself.  Not sure if that is common though.

**Comment by dn-scribe** [comment]
see [here](https://cyclonedx.org/docs/1.4/json/#serialNumber) the cycloneDX definition.

syft: no serial number. I remind it is optional.

ReversingLabs: ```"serialNumber": "urn:uuid:83437284-06c4-4953-be98-8d638e46e1d1"```, like the cycloneDX definition.

**Comment by dn-scribe** [comment]
Decision:
The document ID will be randomized, that can be overriden by user provided configuration.
In addition - approach upstream projects to solve this fundumentally.

**Comment by dn-scribe** [comment]
Error or warn if user provided the same document ID as from the CDX
