### ISSUE TITLE
Separating cli and core 

### ISSUE THREAD

**Issue by manifestori** [bom-squad/protobom#52]
During our discussions about project and repository structure, we have created the "go-cli" repository. Its purpose is to hold the publishable CLI artifact.

Therefore, the `cmd` of this repo should be deprecated and removed. 

Removing the `cmd/cli` package at this point would result in a significant degradation of testing and developer experience, as there is currently no viable replacement (recompiling CLI with `protobom` commit hash is not a feasible solution).

Therefore, before we give the green light on removal, we should:
1) Implement extensive "integration" / "e2e" test for core lib 
2) Replace `demo-ingest` with debug setups
3) Document how to run, test and validate the core libs.

**Comment by manifestori** [comment]
Agreed, I just mentioned this as a prerequisite for removing the CLI from this repo.

**Comment by puerco** [comment]
This is done. Closing.
