### ISSUE TITLE
Remove log and prints from protobom

### ISSUE THREAD

**Issue by manifestori** [bom-squad/protobom#55]
While implementing the CLI, I came across some prints and logs generated by the proto library. It is important to note that we should not log or print anything unless specifically requested by the user.

```bash
format: text/spdx version: 2.3 encoding: json
INFO[0000] Serializing to application/vnd.cyclonedx+json;version=1.4 
```

It is important that the logger is not included in this package. To support external loggers, we should create an interface and utilize the logger accordingly.

**Comment by jspeed-meyers** [comment]
cc @puerco

**Comment by puerco** [comment]
sgtm!

**Comment by houdini91** [comment]
👍
