### ISSUE TITLE
cycloneDX-spdx conversion issues: documentName

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#6]
[documentName](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field)

Issue:
The documentName field is mandatory in SPDX but CycloneDX does not have the equivalent to it.

Suggestion:
- spdx.name = config.spdx.name 
- default to cycloneDX.metadata.component.name + cycloneDX.metadata.component.version

**Comment by stevespringett** [comment]
I believe the SPDX document name is the identity of the document. If that’s the case, then the combination of serialNumber and version is the equivalent CDX BOM identity

**Comment by dn-scribe** [comment]
Thanks Steve, 
SPDX supports both SPDX documentName and [documentIdentifier](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field) fields. 

I assume the name field is supposed to be human-understanable. 
The name field description in SPDX spec: 
"Identify name of this document as designated by creator."

**Comment by puerco** [comment]
Ah thanks for the input Steve! Exactly we need to build the equivalent of the BOM identity. As Danny mentions here, my understanding is that the spdx name is just a string. Following up on https://github.com/bom-squad/protobom/issues/5#issuecomment-1593599056 , the identity of the SPDX document comes from joining the namespace and the ID (which is always fixed). So using SPDX spdx public namespace it would be something like:

`https://spdx.org/spdxdocs/mydocument-99dbc3d3-3a68-4563-80a7-b0a5fe7fc81b#SPDXRef-DOCUMENT`

Nevertheless, my thinking here is that a converted document is a whole new document (with the same data) and it probably should have a new identity (namespace or serial number).

**Comment by dn-scribe** [comment]
@puerco and others,
Returning to this issue:
The identifiers are handles as decided on #5 
options:
1. use the document identity as document name.
2. use the main component name as a basis for the name.
3. one of the above, but let user override the name by configuration.

I still tend to 2+3, 
Please share you opion and let's finalize this.

**Comment by dn-scribe** [comment]
Decision: we go for 2+3, and the component name is taken from protobuf root node component name (supposing the protobom was created by deserializing a cdx.
