### ISSUE TITLE
Proposal: Deprecate Tool and use Node instead

### ISSUE THREAD

**Issue by manifestori** [bom-squad/protobom#68]
CDX 1.5 and SPDX 3.0 seem to have deprecated previous `Tool` implementations while making use of `Component` or `Tool` (a subclass of Element)

SPDX:
https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/Tool.md

CDX: 
https://github.com/CycloneDX/specification/blob/master/schema/bom-1.5.proto

Should we do the same, deprecating Tool, and using Node instead?

**Comment by puerco** [comment]
This issue is still valid. It is not straightforward to answer on the cyclonedx side as the tool component introduces a whole new sibtree which messes the graph. We need some solid proposals on how to handle it.

**Comment by puerco** [comment]
For reference, this is the link to the deprecated fields in the proto with the new component baked in:

https://github.com/CycloneDX/specification/blob/2e0fba32bb2ce20eec37b5c6179395cb942096da/schema/bom-1.5.proto#L591-L605
