### ISSUE TITLE
Docs: Is the README Supported Versions and Formats Table Up to Date?

### ISSUE THREAD

**Issue by jspeed-meyers** [bom-squad/protobom#69]
If it is not, could someone with the relevant knowledge put in a PR? TY!

This table: https://github.com/bom-squad/protobom#supported-versions-and-formats

**Comment by puerco** [comment]
No it is not, this came up today in a call with the SPDX community.

**Comment by jspeed-meyers** [comment]
Should the table read:

| Format | Version | Encoding | Read | Write |
| --- | --- | --- | --- | --- |
| SPDX | 2.2 | JSON | planned | - |
| SPDX | 2.2 | tag-value | planned | - |
| SPDX | 2.3 | JSON | supported | supported|
| SPDX | 2.3 | tag-value | planned | - |
| SPDX | 3.0 | JSON | planned | planned |
| CycloneDX | 1.4 | JSON | supported | supported |
| CycloneDX | 1.5 | JSON | planned | planned |

Or something else?
