### ISSUE TITLE
cycloneDX-spdx conversion issues: creator

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#7]
[Creator](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field)
The spdx.creator is a list of strings as described in the link.

Required in SPDX, not required in CycloneDX.

Suggestion:
- If cycloneDX.metadata.authors is not empty:
```
- initialize spdx.creator to [] and append the following:
- for author in cycloneDX.metadata.authors
    - append "Creator: Person: {author.name} ({author.email})"
- append "Creator: Organization: {cycloneDX.metadata.manufacture.name} ({cycloneDX.metadata.manufacture.contact[0].email})
- append "Creator: Organization: {cycloneDX.metadata.supplier.name} ({cycloneDX.metadata.supplier.contact[0].email})
```
- if it does not exist use config.spdx.authors, default to some string equivalent to "empty" in the right format.

Notes:
- information lost: 
    - cycloneDX.metadata.authors.phone
    - manufacture and supplier url
    - manufacture and supplier contacts: currently assumed to take only the first email. Another option is to have a list creators with all the contacts.
    - Missing in this schema a way to distinguish between the manufacture and supplier. It can be added through a string in the name in the lines of "Creator: Organization: manufacture:acme.inc
- options:
    - define in configuration and default to the above.
    - define configuration options such as whether to put all contacts as creators.

**Comment by dn-scribe** [comment]
Following our previous meeting; since the translated SBOM is a new document, we may want to enable the user to put an identity of his choice (e.g. the identity of whoever is doing the translation). 
This case supports the need to enable supplying the creator as part of config (as suggested above).

**Comment by dn-scribe** [comment]
Returning to the original suggestion above.
Any objections? let's finalize this.

**Comment by jspeed-meyers** [comment]
Should a PR associated with this be in `sbom-convert` and not `protobom`?

**Comment by dn-scribe** [comment]
I think the translation issues should continue here.

**Comment by dn-scribe** [comment]
Decision: 
Since this field allows for describing the tool, we stick to the decision that the SBOM we created is a new one. Thus:
The sbom Translator tool should populate this field with the string describing itself.
In addition, the user can override this string by user input.

**Comment by puerco** [comment]
We could also expose in the translation CLI a flag to `--preserve-author` or something like that.
