### ISSUE TITLE
Support annotations / properties for components / sboms

### ISSUE THREAD

**Issue by manifestori** [bom-squad/protobom#71]
As you know, CDX and SPDX use different to tag/label/annotate components. 
SPDX uses `Annotations` for adding additional data to SPDX Element, SPDX2.x has Document and Package/snippet/file... level annotations. While SPDX3 uses flat Annotations list with ref to and SPDX element.

CDX 1.x has `Property,` which is a narrowed-down version of annotations introduced in CDX 1.5.

I've looked over past work for conversions, which yielded: 
https://github.com/spdx/cdx2spdx/blob/08ec34f11b15dd747410d13c1fc4d11645a20a4b/src/main/java/org/spdx/cdx2spdx/CycloneSpdxConverter.java#L565C60-L565C60

As I figured, they used the opinionated way to convert Properties to Annotations in SPDX (this is a CDX2SPDX tool), forcing Properties as Annotations related to the package/file/document/etc.

Since we have the luxury of having it both ways, we should add Annotations to Nodes and the Bom(document); we should also structure annotation so it could easily convert from/to property.

When unserializing SPDX: we do not have "Properties," only annotations. We would need to support Node-level properties. The problem is that we won't have a way to know how to parse "key" "value" unless. We can default to "annotation1", "annotation2" etc., with the value from "statement."

When serializing SPDX: if we'd have a specific "key" [if we pulled it from CDX] we would encode it alongside the value into a statement ("key=value") and add `protobom` as the annotator.

When serializing CDX we have no issues when serializing to annotations (document level) and properties (from annotations with properties)

When we unserialize, we simply load document level as global annotation and properties (as node-level annotation).

Wdyt?

**Comment by manifestori** [comment]
I have opened an issue for SPDX3 at https://github.com/spdx/spdx-3-model/issues/477. It appears that `name` could be a suitable source for "key", and storing it would enable lossless conversion from SPDX to CDX and vice versa.

SPDX->CDX->SPDX
annotation -> document annotation (cdx1.5 only) / node annotations as properties rebuilding the entire Element as properties list, using the Name prop value as "key" and `statement` as "value"

```
"properties": [
        {
          "name": "annotator",
          "value": "annotator value"
        },
       {
          "name": "comment",
          "value": "comment value"
        },

       {
          "name": "annotationType",
          "value": "other"
        },
        {
          "name": "annotationDate",
          "value": "...."
        }
      ]
```

Going back to SPDX would include rebuilding the annotation object from those props. 

There is an edge case where multiple annotations refer to the same key. To handle this, property names need to be scoped and prefixed either by index (in SPDX 2.x) or by SPDXID in SPDX 3.0.

**Comment by puerco** [comment]
Ah this is a common hack that abuses both standards a little bit. Properties in CDX  != Annotations in SPDX. There is really no equivalent between them, it was one of the points raised during discussions between the SPDX/CDX compatibility talks and CDX offer to add annotations to their spec.

My understanding is that annotations were devised as a way to comment on the document while properties are a way to capture additional data. So, in the purest sense, I would not store them in the same place, but since it is a hack that people use frequently I'd support that as an option at the conversion layer.

**Comment by puerco** [comment]
Ah awesome, reviewing the 1.5 spec annotations are now in:

https://cyclonedx.org/docs/1.5/json/#annotations_items_bom-ref

**Comment by manifestori** [comment]
Yup, the issue with SPDX is the lack of key-value structure that can properly capture data. In the spdx-3 thread I referenced, Im in contact with maintainers about adding a new `properties` field to Annotation to avoid abusing `statement` value for kv store. That would make conversation easier going forward. 

Basically, SPDX annotation could be translated to CDX1.5 annotations with the exception of `signature`, and ofc since CDX annotation does not contain `properties` and has a separate field for that. we could safely assume that ANY document-level annotation is either CDX Annotation or CDX Properties, making all other annotations (element annotation) convert into CDX component `properties`

**Comment by manifestori** [comment]
Not sure why this is `completed`. reopening.
