### ISSUE TITLE
CI Lint Is Failing

### ISSUE THREAD

**Issue by jspeed-meyers** [bom-squad/protobom#78]
I am guessing something changed in the linter

**Comment by manifestori** [comment]
> I am guessing something changed in the linter

I guess you got errors on my branch, I have fixed all lint issues and reran `golangci-lint` looks good. 
Can you verify?

**Comment by jspeed-meyers** [comment]
> I guess you got errors on my branch...

Actually, I noticed it here: https://github.com/bom-squad/protobom/pull/77

What's going on?

**Comment by manifestori** [comment]
This is an existing lint issue that we detect. My open PR fixes all existing lint issues as well.
