### ISSUE TITLE
Writer Implementation Unit Tests

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#83]
We need to write unit tests for the writer implementation.

**Comment by veramine** [comment]
Have you seen examples or a testing framework used in another project that would work well for us?  If so, I would build a bunch of protobufs -- as either Go code or byte array -- and run them through each of the writers to generate expected output..

**Comment by puerco** [comment]
The conformance test data we started to check in will include bundles of SBOM+protobuf bundles, like this one here:
https://github.com/bom-squad/protobom/tree/main/test/conformance/testdata/spdx/2.3/json

We have only one in the repo now, but the idea is to amass a larger collection that spans all versions, encodings, and more than one sample per format. 

Right now we have an SBOM picked from the wild, stored together with its expected protobuf. We could add a third file to the bundle: The expected native serialization from the proto (which is not necessarily equivalent to the original one). WDYT?

**Comment by jspeed-meyers** [comment]
> We could add a third file to the bundle: The expected native serialization from the proto (which is not necessarily equivalent to the original one)

That makes sense to me. "Round trip" testing seems worthwhile.

**Comment by veramine** [comment]
One thing that’s a little tricky…. the expected output is going to keep changing as the writers get more and more complete.  I’ll submit a PR tomorrow for SPDX writer populating “attribution”.  I encountered that missing field In testing today.  Not saying we shouldn’t have tests, just that they will probably either initially fail or, if they initially pass, will start failing as we add more writer functionality.  On Sep 6, 2023, at 5:30 PM, John Speed Meyers ***@***.***> wrote:﻿

We could add a third file to the bundle: The expected native serialization from the proto (which is not necessarily equivalent to the original one)

That makes sense to me. "Round trip" testing seems worthwhile.

**Comment by puerco** [comment]
I agree, but that's the point right :)  I'm trying to make the generation of golden documents as automated as possible to make this the least painful possible.

**Comment by puerco** [comment]
The writer implementation is now gone after merging #102, this can be closed now.
