### ISSUE TITLE
License Boilerplates

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#84]
We need to add license boilerplates to the code. Before doing it, we need to think who will be the collective holder of the copyright.  Ideas? I propose this but feel free to suggest other ideas below:

### The Protobom Project Authors

Some files already have a header crediting "The StarBOM Authors", we should change them:

https://github.com/bom-squad/protobom/blob/4fc3791784be45015eb6a374db9d5972134f935f/pkg/reader/reader.go#L1-L2

I'm listing here the tasks related to ensure we remember:

- [ ] Decide on a collective copyright holder
- [ ] Add boilerplate to all source files
- [ ] Create a script in `./hack` that checks the boilerplates 
- [ ] Add a presubmit to ensure source files are checked on each PR

**Comment by tannerjones4075** [comment]
Has there been any progress on this? I would like to help and contribute :)

**Comment by jspeed-meyers** [comment]
@tannerjones4075, this is probably a good topic to discuss in one of the weekly meetings. Do you know when that meeting is and have a link handy? LMK if you need help.

**Comment by tannerjones4075** [comment]
I would be interested in joining the weekly meeting. Could you send me the details?

**Comment by jspeed-meyers** [comment]
It's every Wednesday at noon. It's only staff from the cohort companies. I'll send a link to your email.

**Comment by jspeed-meyers** [comment]
Actually, can you please send your email address to jsmeyers@chainguard.dev? I'll then add you to the invite.
