### ISSUE TITLE
Hash algorithm enumerations are not used

### ISSUE THREAD

**Issue by puerco** [bom-squad/protobom#89]
## Short Description:

Nodes should use the enumerated hash algorithms.

## Details:

:warning: **Please note that the fix for this bug involves a breaking change** :warning: 

The proto definitions include an enumeration of the supported hash algorithms:

https://github.com/bom-squad/protobom/blob/4fc3791784be45015eb6a374db9d5972134f935f/api/sbom.proto#L153-L174

However, the node structure and the external reference is using a map of strings keyed with strings:

https://github.com/bom-squad/protobom/blob/4fc3791784be45015eb6a374db9d5972134f935f/api/sbom.proto#L28
https://github.com/bom-squad/protobom/blob/4fc3791784be45015eb6a374db9d5972134f935f/api/sbom.proto#L128

We should use the enumerated constants as keys in the hash entries. Having the value as strings opens up the use of protobom to all sorts of inconsistencies, case mixups and so on.

**Comment by veramine** [comment]
My vote is to make the change.  I made this change in my local serializer_cdx.go but I'm embarrassed to check it in lol

```
< if algoVal, ok := sbom.HashAlgorithm_value[algoString]; ok {
-
> if algoVal, ok := sbom.HashAlgorithm_value[strings.ToUpper(algoString)]; ok {
```

**Comment by puerco** [comment]
OK, I'm working on a PR to implement the change. I'll open it today and we can discuss it in the cohort meeting next Wednesday :+1:

**Comment by veramine** [comment]
THANK YOU!

**Comment by puerco** [comment]
Opened https://github.com/bom-squad/protobom/issues/89 to fix this issue

**Comment by puerco** [comment]
Cohort emoji/vocally approved this change on the sep 6th meeting :+1:
